[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["cd apps/backoffice && pnpm install"]

[phases.build]
cmds = ["cd apps/backoffice && pnpm build"]

[start]
cmd = "cd apps/backoffice && pnpm preview -- --host 0.0.0.0"
