[phases.setup]
nixPkgs = ["nodejs-18_x", "curl", "unzip", "pnpm"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "export PATH=$HOME/.bun/bin:$PATH && which bun && bun --version",
  "export PATH=$HOME/.bun/bin:$PATH && pnpm install --frozen-lockfile",
]

[phases.build]
cmds = ["export PATH=$HOME/.bun/bin:$PATH && pnpm run build"]

[start]
cmd = "export PATH=$HOME/.bun/bin:$PATH && pnpm start"
