[phases.setup]
nixPkgs = ["nodejs", "curl", "unzip", "pnpm"]

[phases.install]
cmds = [
  # Instalar Bun y exponerlo para otras fases
  "curl -fsSL https://bun.sh/install | bash",
  "mv ~/.bun /bun",

  # Instalar dependencias de cada app
  "cd apps/api && /bun/bin/bun install",
  "cd apps/frontend && pnpm install",
  "cd apps/backoffice && pnpm install",
]

[phases.build]
cmds = [
  "export PATH=\"/bun/bin:$PATH\"",
  "cd apps/frontend && pnpm build",
  "cd apps/backoffice && pnpm build",
]

[start]
# Podés elegir cómo arrancar: una sola app o todas
# Por ejemplo, sólo la API:
cmd = "export PATH=\"/bun/bin:$PATH\" && cd apps/api && bun run src/index.ts"
