[phases.setup]
nixPkgs = ["nodejs-18_x", "curl", "unzip", "pnpm"]

[phases.install]
cmds = [
  "export COREPACK_ENABLE_STRICT_VERIFICATION=false",
  "corepack enable",
  "curl -fsSL https://bun.sh/install | bash",
  "export PATH=\"/root/.bun/bin:$PATH\"",
  "pnpm install --frozen-lockfile",
]

[phases.build]
cmds = ["export PATH=\"/root/.bun/bin:$PATH\"", "pnpm run build"]

[start]
cmd = "export PATH=\"/root/.bun/bin:$PATH\" && pnpm start"
