[phases.setup]
nixPkgs = ["nodejs-18_x", "curl", "unzip", "pnpm"]

[phases.install]
cmds = ["curl -fsSL https://bun.sh/install | bash", "pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"

[env]
PATH = "$HOME/.bun/bin:$PATH"
