[phases.setup]
nixPkgs = ["nodejs", "curl", "unzip", "bun", "pnpm"]

[phases.install]
cmds = [
  # Install Bun
  "curl -fsSL https://bun.sh/install | bash",
  "mv ~/.bun /bun",

  # Add Bun to PATH for install phase
  "export PATH=\"/bun/bin:$PATH\" && pnpm install",
]

[phases.build]
cmds = ["export PATH=\"/bun/bin:$PATH\"", "pnpm -r build"]

[start]
cmd = "export PATH=\"/bun/bin:$PATH\" && concurrently -k -n api,front,backoffice \
\"pnpm --filter rollergrind360-ecommerce-api preview -- --host 0.0.0.0\" \
\"pnpm --filter rollergrind360-ecommerce-frontend preview -- --host 0.0.0.0\" \
\"pnpm --filter rollergrind360-ecommerce-backoffice preview -- --host 0.0.0.0\""
