[phases.setup]
nixPkgs = ["nodejs", "curl", "bun", "unzip", "pnpm"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "mv ~/.bun /bun",
  "export PATH=\"/bun/bin:$PATH\"",
  "pnpm install",
]

[phases.build]
cmds = ["export PATH=\"/bun/bin:$PATH\"", "pnpm -r build"]

[start]
cmd = "export PATH=\"/bun/bin:$PATH\" && concurrently -k -n api,front,backoffice \"pnpm --filter apps/api dev\" \"pnpm --filter apps/frontend dev\" \"pnpm --filter apps/backoffice dev\""
