services:
  - type: web
    name: frontend
    rootDir: frontend
    runtime: node
    buildCommand: corepack enable && pnpm install --filter ./frontend --frozen-lockfile && pnpm build --filter ./frontend
    startCommand: pnpm start --filter ./frontend

  - type: web
    name: backoffice
    rootDir: backoffice
    runtime: node
    buildCommand: corepack enable && pnpm install --filter ./backoffice --frozen-lockfile && pnpm build --filter ./backoffice
    startCommand: pnpm preview -- --host 0.0.0.0

  - type: web
    name: api
    rootDir: api
    runtime: node
    buildCommand: corepack enable && pnpm install --filter ./api --frozen-lockfile
    startCommand: pnpm dev --filter ./api
