services:
  - name: api
    type: web
    runtime: node
    repo: https://github.com/pbadilla/rg360/
    branch: main
    rootDir: api
    buildCommand: pnpm install
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
