services:
  - type: web
    name: frontend
    rootDir: apps/frontend
    runtime: node
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start

  - type: web
    name: backoffice
    rootDir: apps/backoffice
    runtime: node
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm preview -- --host 0.0.0.0

  - type: web
    name: api
    rootDir: apps/api
    runtime: node
    buildCommand: bun install
    startCommand: bun run src/index.ts
