// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suwutemgyyziwpvcltly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1d3V0ZW1neXl6aXdwdmNsdGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTI3MTMsImV4cCI6MjA2Mjg2ODcxM30.gpMGeSFWLC25TT0QyUFtrHGiyWbf6TI3nwDKW3nRNXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);