paths:
  /email:
    post:
      summary: Send email notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                message:
                  type: string
      responses:
        200:
          description: Email sent

  /download:
    get:
      summary: Download CSV from Universkate and process it
      responses:
        200:
          description: File processed

  /process:
    post:
      summary: Process a CSV row and insert into MongoDB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Reference:
                  type: string
                Ean:
                  type: string
                Prix:
                  type: string
                Stock:
                  type: string
                Image:
                  type: string
                Marque:
                  type: string
                Refmere:
                  type: string
      responses:
        200:
          description: Row processed and inserted
