[phases.setup]
nixPkgs = ["nodejs", "curl", "unzip"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "mv ~/.bun /bun",                                                        # mueve fuera de HOME para persistencia entre fases
  "export PATH=\"/bun/bin:$PATH\" && cd apps/api && /bun/bin/bun install",
]

[phases.build]
cmds = [] # no hay build si se ejecuta directamente

[start]
cmd = "export PATH=\"/bun/bin:$PATH\" && cd apps/api && bun run src/index.ts"
