[phases.setup]
nixPkgs = ["nodejs", "bun", "curl"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "export PATH=\"/root/.bun/bin:$PATH\"",
  "cd apps/api && bun install"
]

[phases.build]
cmds = []

[start]
cmd = "cd apps/api && /root/.bun/bin/bun run src/index.ts"
