[phases.setup]
nixPkgs = ["nodejs", "bun", "curl"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "export PATH=\"/root/.bun/bin:$PATH\"",
  "bun install",
]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "/root/.bun/bin/bun run build/index.js"
